name: Nix tests

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Check format & lint
        run: |
          ruff format --check
          ruff check

      - name: Typecheck
        run: mypy --strict src

      - name: Run tests
        run: pytest tests
